# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173"] # adres frontendu
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
    allow_credentials: false
  paths:
    "^/api/":
      # dla wszystkich ścieżek zaczynających się od /api/
      allow_origin: ["http://localhost:5173"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
